exports.compositoresListPage = function(slist, d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.jpg"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Compositores</title>
        </head>

        <body>
            <div class="w3-card-4">

                <header class="w3-container w3-teal">
                    <h1>Compositores
                    <a class="w3-btn w3-round w3-grey" href="/compositores/registo">+</a>
                    </h1>
                </header>
        
                <div class="w3-container">
                    <table class="w3-table-all">
                        <tr>
                            <th>Nome</th>
                            <th>Bio</th>
                            <th>Data de Nascimento</th>
                            <th>Data de Obito</th>
                            <th>Periodo</th>
                            <th>Actions</th>
                        </tr>`
    for(let i=0; i < slist.length ; i++){
        pagHTML +=      `<tr>
                            <td>
                                <a href="/compositores/${slist[i].id}">${slist[i].nome}</a>
                            </td>
                            <td>${slist[i].bio}</td>
                            <td>${slist[i].dataNasc}</td>
                            <td>${slist[i].dataObito}</td>
                            <td>${slist[i].periodo.name}</td>
                            <td>
                                [<a href="/compositores/edit/${slist[i].id}">Edit</a>]
                                [<a href="/compositores/delete/${slist[i].id}">Delete</a>]
                            </td>
                        </tr>`
    }

    pagHTML +=      `</table>
                </div>

                <footer class="w3-container w3-blue">
                    <h5>Generated in EngWeb2024 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML
}


exports.compositorFormPage = function(periodos,d) {
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.jpg"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Registo de um Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-indigo">
                    <h2>Registo de um Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <label><strong>Id: </strong></label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label><strong>Name: </strong></label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label><strong>Bio: </strong></label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label><strong>Data de Nascimento: </strong></label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label><strong>Data de Obito: </strong></label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label><strong>Periodo: </strong></label>
                        <select class="w3-select w3-round" name="periodo">
                            ${periodos.map(p => `<option value="${p.id}">${p.name}</option>`).join('')}
                        </select>
                    </fieldset>
                    <button class="w3-btn w3-indigo w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-indigo">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML
}

exports.compositorFormEditPage = function(periodos,d){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.jog"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Editar Compositor</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-indigo">
                    <h2>Editar Compositor</h2>
                </header>
            
                <form class="w3-container" method="POST">
                    <fieldset>
                        <label><strong>Id: </strong></label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label><strong>Name: </strong></label>
                        <input class="w3-input w3-round" type="text" name="nome"/>
                        <label><strong>Bio: </strong></label>
                        <input class="w3-input w3-round" type="text" name="bio"/>
                        <label><strong>Data de Nascimento: </strong></label>
                        <input class="w3-input w3-round" type="text" name="dataNasc"/>
                        <label><strong>Data de Obito: </strong></label>
                        <input class="w3-input w3-round" type="text" name="dataObito"/>
                        <label><strong>Periodo: </strong></label>
                        <select class="w3-select w3-round" name="periodo">
                            ${periodos.map(periodo => `<option value="${periodo.id}">${periodo.name}</option>`).join('')}
                        </select>
                    </fieldset>
                    <button class="w3-btn w3-indigo w3-mb-2" type="submit">Register</button>
                </form>

                <footer class="w3-container w3-indigo">
                    <h5>Generated by EngWeb2024 in ${d} - [<a href="/compositores">Return</a>]</h5>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML
}

// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.compositorPage = function(compositor, d ){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <title>${compositor.nome}</title>
            <meta charset="utf-8"/>
            <link rel="icon" href="favicon.jpg"/>
            <link rel="stylesheet" href="w3.css"/>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-teal">
                    <h1>${compositor.nome}</h1>
                </header>

                <div class="w3-container">
                    <ul class="w3-ul w3-card-4" style="width:50%">
                        <li><b>Nome: </b> ${compositor.nome}</li>
                        <li><b>Bio: </b> ${compositor.bio}</li>
                        <li><b>Data de Nascimento: </b> ${compositor.dataNasc}</li>
                        <li><b>Data de Obito: </b> ${compositor.dataNasc}</li>
                        <li><b>Periodo: </b> ${compositor.periodo.name}</li>
                    </ul>
                </div>
        
                <footer class="w3-container w3-teal">
                    <address>Gerado por aluno::EngWeb2024 em ${d} - [<a href="/compositores">Voltar</a>]</address>
                </footer>
            </div>
        </body>
    </html>`
    return pagHTML
}

// -------------- Error Treatment ------------------------------
exports.errorPage = function(errorMessage, d){
    return `<p>${d}: Error: ${errorMessage}</p>`
}